fun fail(message: String): Nothing  {
    throw IllegalArgumentException(message)
}

fun box(): String  {
    return try  {
        val x: Nothing = fail("Testing fail")
        "FAIL"
    }
    catch (e: IllegalArgumentException)  {
        "OK"
    }
    finally  {
        "OK"
    }
}
