fun fail(message: String) : Nothing  {
    throw java.lang.IllegalArgumentException(message)
}

fun box() : String  {
    return try {
    val x : Nothing = fail("Testing fail")
"FAIL"
}
catch (e : IllegalArgumentException)  {
"OK"
}
finally  {
    "FAIL"
}
}
